In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout

In [2]:
dataset_train = pd.read_csv('/content/PJME_hourly (1).csv')
training_set = dataset_train.iloc[:,1:2].values   #Note the index range in dataset_train.iloc[:, 1: 2].values because we need to make it NumPy array, not a single vector nor a dataframe for training.
print(dataset_train)

                  Datetime  PJME_MW
0      2002-12-31 01:00:00  26498.0
1      2002-12-31 02:00:00  25147.0
2      2002-12-31 03:00:00  24574.0
3      2002-12-31 04:00:00  24393.0
4      2002-12-31 05:00:00  24860.0
...                    ...      ...
37444  2006-09-23 14:00:00  31421.0
37445  2006-09-23 15:00:00  31357.0
37446  2006-09-23 16:00:00  31540.0
37447  2006-09-23 17:00:00  31856.0
37448      2006-09-23 18:0      NaN

[37449 rows x 2 columns]


In [3]:
sc = MinMaxScaler(feature_range = (0,1))
training_set_scaled = sc.fit_transform(training_set)
print(training_set_scaled)

[[0.1822592 ]
 [0.14830082]
 [0.13389805]
 ...
 [0.30899357]
 [0.31693646]
 [       nan]]


In [4]:
x_train = []
y_train = []

In [5]:
for i in range(60,2035):
    x_train.append(training_set_scaled[i-60:i, 0])
    #y_train.append(training_set_scaled[i,0])
    y_train.append(training_set_scaled[i,0])
x_train, y_train = np.array(x_train), np.array(y_train)
print(x_train[0])                                                                               
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))
print(x_train.shape[0])


[0.1822592  0.14830082 0.13389805 0.12934848 0.14108687 0.17532174
 0.23765836 0.28782928 0.31552886 0.32957973 0.32988136 0.3180927
 0.29858737 0.27953449 0.25932536 0.24761211 0.27802634 0.37125478
 0.37572894 0.34041323 0.30386588 0.2674442  0.23215363 0.19507842
 0.20809873 0.18482304 0.17579932 0.17509552 0.19163483 0.23708023
 0.30821436 0.362407   0.3865373  0.38729137 0.37824251 0.36356324
 0.34787854 0.33734667 0.33010758 0.3327217  0.37273778 0.44570682
 0.44889905 0.43346571 0.40772672 0.36941987 0.31097929 0.23924191
 0.19698874 0.16561934 0.15264931 0.14827569 0.14817515 0.16323145
 0.18346571 0.2070179  0.2329077  0.25067866 0.25382063 0.24989946]
1975


In [6]:
print(x_train)

[[[0.1822592 ]
  [0.14830082]
  [0.13389805]
  ...
  [0.25067866]
  [0.25382063]
  [0.24989946]]

 [[0.14830082]
  [0.13389805]
  [0.12934848]
  ...
  [0.25382063]
  [0.24989946]
  [0.2465564 ]]

 [[0.13389805]
  [0.12934848]
  [0.14108687]
  ...
  [0.24989946]
  [0.2465564 ]
  [0.23730645]]

 ...

 [[0.10657551]
  [0.20415242]
  [0.27596521]
  ...
  [0.29257993]
  [0.28848281]
  [0.29019204]]

 [[0.20415242]
  [0.27596521]
  [0.29602353]
  ...
  [0.28848281]
  [0.29019204]
  [0.28481299]]

 [[0.27596521]
  [0.29602353]
  [0.31027549]
  ...
  [0.29019204]
  [0.28481299]
  [0.29841142]]]


In [7]:
print(y_train)

[0.2465564  0.23730645 0.22715162 ... 0.28481299 0.29841142 0.33211844]


In [ ]:
model = Sequential()                                  
model.add(LSTM(units = 128, return_sequences=True,input_shape = (x_train.shape[1],1)))
model.add(Dropout(0.2))
model.add(LSTM(units = 64, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units = 32, return_sequences=True))     
model.add(Dropout(0.2))
model.add(LSTM(units = 32))
model.add(Dropout(0.2))
model.add(Dense(units = 1))
model.compile(optimizer = 'adam', loss = 'mean_squared_error')
model.fit(x_train,y_train,epochs = 650,batch_size = 32)                                            

Epoch 1/650
62/62 [==============================] - 18s 151ms/step - loss: 0.0158
Epoch 2/650
62/62 [==============================] - 9s 149ms/step - loss: 0.0107
Epoch 3/650
62/62 [==============================] - 10s 162ms/step - loss: 0.0073
Epoch 4/650
62/62 [==============================] - 9s 150ms/step - loss: 0.0060
Epoch 5/650
62/62 [==============================] - 9s 147ms/step - loss: 0.0052
Epoch 6/650
62/62 [==============================] - 10s 155ms/step - loss: 0.0046
Epoch 7/650
62/62 [==============================] - 9s 150ms/step - loss: 0.0043
Epoch 8/650
62/62 [==============================] - 9s 149ms/step - loss: 0.0040
Epoch 9/650
62/62 [==============================] - 9s 149ms/step - loss: 0.0040
Epoch 10/650
62/62 [==============================] - 9s 151ms/step - loss: 0.0037
Epoch 11/650
62/62 [==============================] - 9s 149ms/step - loss: 0.0040
Epoch 12/650
16/62 [======>.......................] - ETA: 6s - loss: 0.0038